version: '3.8'

services:
  # API Service
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit Web Interface
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./models:/app/models
      - ./logs:/app/logs
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped
    depends_on:
      - api

  # Training Service (optional)
  training:
    build: .
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./models:/app/models
      - ./logs:/app/logs
    command: python train_models.py
    profiles:
      - training

networks:
  default:
    name: emotional-intelligence-network 